# Generated by Django 4.2 on 2023-07-05 14:53

import django.core.validators
from django.db import migrations, models
import zezere.models


class Migration(migrations.Migration):
    dependencies = [
        ("zezere", "0012_auto_20200323_1130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="mac_address",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^([0-9A-F]{2}[:]){5}([0-9A-F]{2})$"
                    ),
                    zezere.models.validator_disallow_blacklisted_mac,
                ],
                verbose_name="Device MAC Address",
            ),
        ),
    ]
