# Generated by Django 4.0.4 on 2022-08-26 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zezere', '0014_config'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Config',
            new_name='FDOConfig',
        ),
    ]
